spring:
  application:
    name: Senda Delivery
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/senda_delivery
    username: root
    password: WANGfan040823
  data:
    redis:
      host: 192.168.145.129
      port: 6379
      database: 0
      password: WANGfan040823
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 300MB

#spring事务管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true #下划线-驼峰命名转换
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #将日志输出到标准输出（控制台）
  mapper-locations: classpath*:/mapper/**/*.xml #Mapper.xml文件地址，默认值
  global-config:
    db-config:
      id-type: auto #id主键自增

r2:
  endpoint: https://322c9f29618be2ca9a55df8b95862c5e.r2.cloudflarestorage.com
  access-key: 22bcb467192a6590c14b65923d916b8c
  secret-key: f02cec7223abbd204146b0b46462939bb5bc56526769720d004252450467b032
  bucket-name: senda-delivery-project
  public-endpoint: https://pub-2cadb64652464d8aafe01bad4dabf27e.r2.dev

senda:
  jwt:
    admin-secret-key: sendaDeliveryAdminExampleSuperSecretKeyForHS256Algorithm
    admin-ttl: 86400000 #24h(75686400000000-100y)
    admin-token-name: token
    user-secret-key: sendaDeliveryExampleUserSuperSecretKeyForHS256Algorithm
    user-ttl: 86400000 #24h
    user-token-name: authentication
